name: npm-publish

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish-npm:
    runs-on: self-hosted
    steps:
      - id: secrets
        uses: google-github-actions/get-secretmanager-secrets@main
        with:
          secrets: |-
            npm-token:nitraai/npm-token

      - uses: actions/checkout@v3

      - name: publish
        run: npx @jsdevtools/npm-publish --token=${{ steps.secrets.outputs.npm-token }} --access=public npm/package.json
